---
--- Generated by Luanalysis
--- Created by CAOHAOBO.
--- DateTime: 2022/12/27 19:24
---
--锁的key
--local key=KEYS[1]
----当前线程表示
--local threadId=ARGV[1]


--获取锁中的线程表示
local id = redis.call('get',KEYS[1])
if(id==ARGV[1])
    then
    return redis.call('del',KEYS[1])
end
return 0